# _config.yml
title: "平价、稳定自用可付费机场推荐持续更新（2023/10）"
remote_theme: pages-themes/leap-day@v0.2.0
plugins:
    - jekyll-github-metadata
    - jekyll-sitemap
    - jekyll-seo-tag
    - jemoji
    - jekyll-remote-theme # add this line to the plugins list if you already have one
