# _config.yml
title: "平价、稳定自用可付费机场推荐持续更新（2023/10）"
description: 推荐整理平价、稳定自用可付费机场推荐，方便用户选择
remote_theme: pages-themes/cayman@v0.2.0
plugins:
    - jekyll-github-metadata
    - jekyll-sitemap
    - jekyll-seo-tag
    - jemoji
    - jekyll-readme-index
    - jekyll-remote-theme # add this line to the plugins list if you already have one
readme_index:
  enabled:          true
  remove_originals: false
  with_frontmatter: false

google_analytics: G-S3RXRD9QNL
